<?php

namespace App\Filament\Resources\ObraResource\RelationManagers;

use App\Models\Foto;
use Filament\Forms;
use Filament\Forms\Components\FileUpload;
use Filament\Forms\Components\Hidden;
use Filament\Forms\Components\Section;
use Filament\Forms\Components\Select;
use Filament\Forms\Components\SpatieTagsInput;
use Filament\Forms\Form;
use Filament\Resources\RelationManagers\RelationManager;
use Filament\Tables;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletingScope;
use Illuminate\Support\Str;
use NunoMaduro\Collision\Adapters\Phpunit\State;
use Symfony\Component\Console\Input\Input;

class FotosRelationManager extends RelationManager
{
    protected static string $relationship = 'fotos';





    public function isReadOnly(): bool
    {
        //return parent::isReadOnly(); // TODO: Change the autogenerated stub
        return false;
    }

    public function form(Form $form): Form
    {
        return $form
            ->schema([
              //  Foto::getForm(),
                Hidden::make('user_id')
                    ->default(auth()->id())
                    ->required(),

                Select::make('tipobra_id')
                    ->label('Tipo de Obra')
                    ->relationship('tipobra', 'nombre')
                    ->default(1)
                    ->required()
                ,
                Section::make('Imágenes del Trabajo')->schema([
                    FileUpload::make('images')
                        ->directory(function (?Model $record,Forms\Get $get, Forms\Set $set) {

                            $obra = $this->getOwnerRecord();

                            $obra_codigo = $obra ? $obra->id : '00000';


                          //  dd($record, $obra_codigo, $obra, $set);

                            // Retorna el directorio basado en la referencia, si está disponible.
                            return 'OBRAS-FOTO/' . ($obra_codigo ?? 'D000');

                           // dd( $record,$get('referencia'), $set, $record->referencia, $get);
                        }
                            //'trabajos/'.auth()->id()
                        )
                        ->multiple()
                        ->maxFiles(5)
                        ->reorderable()
                        ->imageEditor()
                        ->imageResizeMode('cover')
                        ->imageCropAspectRatio('16:9')
                        ->imageResizeTargetWidth('1280')
                        ->imageResizeTargetHeight('720')
                        ->panelLayout('grid')
                        ->columnSpanFull()
                    ,

                ])->columns(1),
                SpatieTagsInput::make('tags'),


            ],




            );
    }




    public function table(Table $table): Table
    {
        return $table
            ->recordTitleAttribute('nombre')
            ->columns([
                Tables\Columns\TextColumn::make('user.name')
                ->searchable(),

                Tables\Columns\TextColumn::make('tipobra.nombre')
                    ->badge()
                    ->searchable()
                    ->color('success')
                    ->label('Tipo de Obra'),

                Tables\Columns\ImageColumn::make('images')
                    ->circular()
                    ->stacked()
                    ->limit(3)
                    ->label('Imagen'),
                Tables\Columns\SpatieTagsColumn::make('tags'),


                /*   Tables\Columns\SpatieMediaLibraryImageColumn::make('Fotos')
                       ->collection('obraCollection')
                       ->circular()
                       ->stacked()
                       ->limit(3)
                       ->limitedRemainingText() ,

                   */


                    Tables\Columns\TextColumn::make('updated_at')
                        ->dateTime()
                        ->sortable()


            ])
            ->filters([
                Tables\Filters\SelectFilter::make('tipobra')
                ->relationship('tipobra','nombre'),
                Tables\Filters\SelectFilter::make('user')
                    ->relationship('user','name')

            ])
            ->headerActions([
                Tables\Actions\CreateAction::make(),
            ])
            ->actions([
                Tables\Actions\EditAction::make()->slideOver(),
                Tables\Actions\DeleteAction::make(),
            ])
            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([
                    Tables\Actions\DeleteBulkAction::make(),
                ]),
            ]);
    }
}
